language: python
python:
   - "3.6"
script:
   - pytest
    
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "adsofron-github"
    token:
      secure: $sonar-login
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
