language: python
python:
- '3.6'
dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: adsofron-github
    token:
      secure: "qPNgHN6vhLXwsICKmbc8MJj7vUNX8ISiV94EiQz2Fo5WsmrZJgXoSwbaFvze3E2neUIx6PKhqpQ8jcY5bhWIOiF/0eREQ0x1vqwtJbMb5FZ73wAVdB9MDv3fJyaQCEo+Zv22uWzmhNmJWfgULMWLeH8zmc9llmAtB/xf/WZH+UGLNUkFAKd2ZJj5rqtK9/DYeo7yvDpFmDjuxQ6nVpZIiQxf3/THElaTCMBbHm013km2zzUa0IsmYrxlOoh6KNuzqvwDHcG5pI1hWTEkdF45i+vmTSTkseflqCAPpcO9cEmqCsAksAGS4ecPN0chWhqet4AE7/68UG7wIewMn33O2vv8Fu+czUIHTYJxLU7uvuT33nxFmIjUCXvD3mPnIMXSsk070bT6SCgLj7sdxfl6jlHWblO1jf6anQlxTxmWQN92ocBxKTpn32aWJouXRpqC6kb4opc0e6vKl5IaR0LRGJOLvt7gTHajvEiIWwRGqbVziPyqKXnTewEyoJeHUym99YHXoYB+/HwlfZgvtg7/byLaNiCsrKXPHVcfI1GincVo4FPgMUiKkKsobMfbVCCitfl1QHzC4+wcU+2VNE+Q/Lf00KUpeE2uCOWQVmf5IRFbjNaFd5Bdp+028++DmfDBAP/u3BEtZSpqjVbxSEvBwIbzGHCfNL+2KFRg2zMWSX8="

jdk:
- oraclejdk8
script:
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  global:
  - secure: qPNgHN6vhLXwsICKmbc8MJj7vUNX8ISiV94EiQz2Fo5WsmrZJgXoSwbaFvze3E2neUIx6PKhqpQ8jcY5bhWIOiF/0eREQ0x1vqwtJbMb5FZ73wAVdB9MDv3fJyaQCEo+Zv22uWzmhNmJWfgULMWLeH8zmc9llmAtB/xf/WZH+UGLNUkFAKd2ZJj5rqtK9/DYeo7yvDpFmDjuxQ6nVpZIiQxf3/THElaTCMBbHm013km2zzUa0IsmYrxlOoh6KNuzqvwDHcG5pI1hWTEkdF45i+vmTSTkseflqCAPpcO9cEmqCsAksAGS4ecPN0chWhqet4AE7/68UG7wIewMn33O2vv8Fu+czUIHTYJxLU7uvuT33nxFmIjUCXvD3mPnIMXSsk070bT6SCgLj7sdxfl6jlHWblO1jf6anQlxTxmWQN92ocBxKTpn32aWJouXRpqC6kb4opc0e6vKl5IaR0LRGJOLvt7gTHajvEiIWwRGqbVziPyqKXnTewEyoJeHUym99YHXoYB+/HwlfZgvtg7/byLaNiCsrKXPHVcfI1GincVo4FPgMUiKkKsobMfbVCCitfl1QHzC4+wcU+2VNE+Q/Lf00KUpeE2uCOWQVmf5IRFbjNaFd5Bdp+028++DmfDBAP/u3BEtZSpqjVbxSEvBwIbzGHCfNL+2KFRg2zMWSX8=
